--xTablas

DROP TABLE Tarifas CASCADE CONSTRAINTS;
DROP TABLE Canchas CASCADE CONSTRAINTS;
DROP TABLE AdicionalesPorReservaciones CASCADE CONSTRAINTS;
DROP TABLE Adicionales CASCADE CONSTRAINTS;
DROP TABLE Partidos CASCADE CONSTRAINTS;
DROP TABLE Reservaciones CASCADE CONSTRAINTS;
DROP TABLE Pagos CASCADE CONSTRAINTS;
DROP TABLE ZonasDeportivas CASCADE CONSTRAINTS;
DROP TABLE Encargados CASCADE CONSTRAINTS;
DROP TABLE Calificaciones CASCADE CONSTRAINTS;
DROP TABLE Jugadores CASCADE CONSTRAINTS;
DROP TABLE TelefonosPorJugador CASCADE CONSTRAINTS;
DROP TABLE Equipos CASCADE CONSTRAINTS;
DROP TABLE EquiposJueganPartidos CASCADE CONSTRAINTS;